# Build stage
FROM maven:3.9.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

# Runtime stage
FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=build /app/target/shopnest-backend-1.0.0.jar app.jar

EXPOSE 8080

CMD ["sh", "-c", "java -Xms128m -Xmx350m -jar app.jar"]